UCLA scl 1.0
# Created      : Thu May 23 15:26:25 2002
# User         : sadya@voskhod.eecs.umich.edu (Saurabh N Adya,Not Available,NotAvailable/Freysinger;CR0i;30) 
# Platform     : Linux 2.4.10 #1 Fri Sep 28 09:29:45 EDT 2001 i686 


Numrows : 20

CoreRow Horizontal
 Coordinate   :          0
 Height       :         16
 Sitewidth    :          1
 Sitespacing  :          1
 Siteorient   :         N 
 Sitesymmetry :         Y 
 SubrowOrigin :          0 Numsites :       200
End